# Generated by Django 3.2.9 on 2022-02-20 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='baskets',
            field=models.ManyToManyField(to='core.Basket'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='buyers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='baskets',
            field=models.ManyToManyField(to='core.Basket'),
        ),
        migrations.AlterField(
            model_name='content',
            name='buyers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
