# Generated by Django 3.2.9 on 2022-02-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220220_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='buyers',
        ),
        migrations.RemoveField(
            model_name='content',
            name='buyers',
        ),
    ]
